### ISSUE TITLE
Going between Embedding Dimension & Input Dimension in minGRU layers

### ISSUE THREAD

**Issue by lbaierreinio** [lbaierreinio/min-gru-transformers#13]
Currently, the minGRU layer expects sequences with `input_dimension`, and uses a linear layer to transform the `input_dimension` vector to the `hidden_dimension` for the RNN cell. Then, the output of the RNN cell is converted back to the `input_dimension`. Therefore, if we have a deep RNN (many layers), we repeatedly transform back-and-forth between the `input_dimension` and the `hidden_dimension`. 

Based on what I've read, this is not conventional in a deep RNN. We should only transform the input to the `hidden_dimension` once, before the sequence enters the layers of RNN cells. Only after all of the RNN layers have been traversed should we convert the `hidden_dimension` back to the input dimension. We most likely want to tweak the code accordingly.

**Comment by dlrudwo1269** [comment]
Fixed here https://github.com/lbaierreinio/min-gru-transformers/pull/16
